# Generated by Django 4.1.6 on 2023-02-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dreamimage_entry_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='image_url',
            new_name='image_id',
        ),
    ]
