# Generated by Django 4.1.6 on 2023-02-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_url_entry_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image_id',
        ),
    ]
