# Generated by Django 4.1.6 on 2023-02-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entry_created_by_entry_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created_by',
        ),
    ]
