# Generated by Django 4.1.6 on 2023-02-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_entry_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='image_id',
            new_name='image',
        ),
    ]
