# Generated by Django 4.1.6 on 2023-02-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_image_id_entry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='image',
            new_name='image_id',
        ),
    ]
